#!/usr/bin/env python3
"""
Figures for: Continuity of ADM variables across the Oppenheimer–Snyder boundary in the unit-lapse gauge (2026)

Anderson M. Rodriguez

Generates three publication figures:
  Fig. 1  — Lapse function N(r) across the dust surface: PG vs Schwarzschild
  Fig. 2  — Velocity field / shift vector across the boundary: smooth PG matching
  Fig. S1 — Metric coefficient continuity (g_TT, g_Tr, g_rr) across the boundary

An auxiliary spacetime diagram (not included in the manuscript) can be
generated by uncommenting fig_spacetime_diagram() in the main block.
"""

import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon

# ── Output directory (portable) ───────────────────────────────────────
FIGDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'figures')
os.makedirs(FIGDIR, exist_ok=True)

# ── Global style ──────────────────────────────────────────────────────
plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 11,
    'axes.labelsize': 13,
    'legend.fontsize': 10,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'text.usetex': False,
    'mathtext.fontset': 'cm',
    'figure.dpi': 300,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.05,
})

# ── Physical parameters (G = c = 1 units) ────────────────────────────
M = 1.0                          # Total mass of the dust ball
R0 = 10.0 * M                 # Initial areal radius of the dust surface
rs = 2.0 * M                     # Schwarzschild radius


# ══════════════════════════════════════════════════════════════════════
# FIGURE 1: Lapse function across the boundary
# ══════════════════════════════════════════════════════════════════════

def fig_lapse_comparison():
    """
    Shows N(r) for PG (N=1 everywhere) vs Schwarzschild [N = sqrt(1-2M/r)]
    evaluated at a snapshot when the dust surface is at R = 5M.
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4.2), sharey=True)

    R_surface = 5.0 * M

    r_int = np.linspace(0.01, R_surface, 200)
    r_ext = np.linspace(R_surface, 15 * M, 200)

    # ── Panel (a): PG gauge ──
    ax1.plot(r_int / M, np.ones_like(r_int), 'b-', lw=2.2,
             label='Interior (FRW comoving)')
    ax1.plot(r_ext / M, np.ones_like(r_ext), 'r-', lw=2.2,
             label='Exterior (PG)')
    ax1.axvline(R_surface / M, color='gray', ls='--', lw=1, alpha=0.7)
    ax1.annotate(r'$r = R(\tau)$', xy=(R_surface / M, 0.55),
                 fontsize=10, color='gray', ha='center',
                 bbox=dict(boxstyle='round,pad=0.2', facecolor='white',
                           edgecolor='none', alpha=0.9))
    ax1.set_xlabel(r'$r / M$')
    ax1.set_ylabel(r'Lapse function $N$')
    ax1.set_title(r'(a) $N = 1$ gauge (PG exterior)', fontsize=12)
    ax1.set_ylim(0, 1.35)
    ax1.set_xlim(0, 15)
    ax1.legend(loc='upper right', framealpha=0.9)

    ax1.plot(R_surface / M, 1.0, 'ko', ms=8, zorder=5)
    ax1.annotate(r'$N_{\mathrm{int}} = N_{\mathrm{ext}} = 1$',
                 xy=(R_surface / M, 1.0), xytext=(R_surface / M + 2.5, 1.15),
                 fontsize=10, color='black',
                 arrowprops=dict(arrowstyle='->', color='black', lw=1.2))

    # ── Panel (b): Schwarzschild gauge ──
    N_ext_Sch = np.sqrt(1 - rs / r_ext)

    ax2.plot(r_int / M, np.ones_like(r_int), 'b-', lw=2.2,
             label='Interior (FRW comoving)')
    ax2.plot(r_ext / M, N_ext_Sch, 'r-', lw=2.2,
             label='Exterior (Schwarzschild)')
    ax2.axvline(R_surface / M, color='gray', ls='--', lw=1, alpha=0.7)
    ax2.annotate(r'$r = R(\tau)$', xy=(R_surface / M, 0.55),
                 fontsize=10, color='gray', ha='center',
                 bbox=dict(boxstyle='round,pad=0.2', facecolor='white',
                           edgecolor='none', alpha=0.9))
    ax2.set_xlabel(r'$r / M$')
    ax2.set_title(r'(b) Diagonal gauge (Schwarzschild exterior)', fontsize=12)
    ax2.set_xlim(0, 15)
    ax2.legend(loc='upper right', framealpha=0.9)

    N_ext_at_surface = np.sqrt(1 - rs / R_surface)
    ax2.plot(R_surface / M, 1.0, 'bo', ms=7, zorder=5)
    ax2.plot(R_surface / M, N_ext_at_surface, 'ro', ms=7, zorder=5)

    ax2.annotate('', xy=(R_surface / M + 0.15, N_ext_at_surface),
                 xytext=(R_surface / M + 0.15, 1.0),
                 arrowprops=dict(arrowstyle='<->', color='darkorange', lw=2))
    gap = 1.0 - N_ext_at_surface
    ax2.annotate(r'$\Delta N = %.3f$' % gap,
                 xy=(R_surface / M + 0.3, (1.0 + N_ext_at_surface) / 2),
                 fontsize=10, color='darkorange', ha='left', va='center')

    fig.tight_layout(w_pad=1.5)
    fig.savefig(os.path.join(FIGDIR, 'fig1_lapse_comparison.pdf'))
    fig.savefig(os.path.join(FIGDIR, 'fig1_lapse_comparison.png'))
    plt.close(fig)
    print("Figure 1: Lapse comparison — done.")


# ══════════════════════════════════════════════════════════════════════
# FIGURE 2: Velocity field / shift vector across the boundary
# ══════════════════════════════════════════════════════════════════════

def fig_velocity_field():
    """
    For marginally bound OS collapse (E=0, dust falling from rest at infinity):
      Interior: v(r,tau) = (2M/R^3)^{1/2} * r   (Hubble-like)
      Exterior: v(r) = sqrt(2M/r)                (PG velocity field)
    At the dust surface r = R(tau), both give v = sqrt(2M/R).
    """
    fig, ax = plt.subplots(figsize=(7, 4.5))

    R_values = [8.0, 5.0, 3.0, 2.5]
    colors = ['#1b9e77', '#d95f02', '#7570b3', '#e7298a']
    r_max = 12.0

    for i, R in enumerate(R_values):
        r_int = np.linspace(0, R, 150)
        v_int = -np.sqrt(2 * M / R**3) * r_int

        r_ext = np.linspace(R, r_max, 150)
        v_ext = -np.sqrt(2 * M / r_ext)

        ax.plot(r_int / M, np.abs(v_int), '-', color=colors[i], lw=2.0,
                label=r'$R(\tau) = %.1fM$' % (R / M))
        ax.plot(r_ext / M, np.abs(v_ext), '-', color=colors[i], lw=2.0)

        v_match = np.sqrt(2 * M / R)
        ax.plot(R / M, v_match, 'o', color=colors[i], ms=7, zorder=5,
                markeredgecolor='k', markeredgewidth=0.8)

    ax.axvline(rs / M, color='gray', ls=':', lw=1, alpha=0.5)
    ax.annotate(r'$r_s = 2M$', xy=(rs / M, 0.02), fontsize=9, color='gray')

    ax.set_xlabel(r'Areal radius $r / M$')
    ax.set_ylabel(r'$|v(r)|$ (velocity field magnitude)')
    ax.set_title(r'Shift vector matching at the dust surface', fontsize=12)
    ax.legend(loc='upper right', framealpha=0.9, title=r'Dust surface position')
    ax.set_xlim(0, r_max / M)
    ax.set_ylim(0, 1.15)

    ax.text(2.0, 0.95, r'Interior: $v = \sqrt{2M/R^3}\;r$',
            fontsize=10, color='#555555', ha='left',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow',
                      edgecolor='gray', alpha=0.9))
    ax.text(7.8, 0.58, r'Exterior: $v = \sqrt{2M/r}$',
            fontsize=10, color='#555555', ha='left',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow',
                      edgecolor='gray', alpha=0.9))

    fig.tight_layout()
    fig.savefig(os.path.join(FIGDIR, 'fig2_velocity_matching.pdf'))
    fig.savefig(os.path.join(FIGDIR, 'fig2_velocity_matching.png'))
    plt.close(fig)
    print("Figure 2: Velocity field matching — done.")


# ══════════════════════════════════════════════════════════════════════
# FIGURE S1: Metric coefficient continuity across the boundary
# ══════════════════════════════════════════════════════════════════════

def fig_metric_continuity():
    """
    All three independent metric coefficients (g_TT, |g_Tr|, g_rr) as
    functions of areal radius r, evaluated across the dust surface at
    R = 5M.  Both interior and exterior are written in (T, r) coordinates
    with N = 1.

    Interior (FRW dust, PG-like coords):
        g_TT = 1 - H^2 r^2,   |g_Tr| = Hr,   g_rr = +1
        where H = sqrt(2M / R^3)

    Exterior (PG):
        g_TT = 1 - 2M/r,   |g_Tr| = sqrt(2M/r),   g_rr = +1
    """
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))

    R_surface = 5.0 * M
    H = np.sqrt(2 * M / R_surface**3)

    r_int = np.linspace(0.01, R_surface, 200)
    r_ext = np.linspace(R_surface, 12 * M, 200)

    # ── Panel (a): g_{TT} ──
    gTT_int = 1 - (H * r_int)**2
    gTT_ext = 1 - 2 * M / r_ext

    axes[0].plot(r_int / M, gTT_int, 'b-', lw=2, label='Interior')
    axes[0].plot(r_ext / M, gTT_ext, 'r-', lw=2, label='Exterior')
    axes[0].axvline(R_surface / M, color='gray', ls='--', lw=0.8, alpha=0.5)
    axes[0].set_xlabel(r'$r/M$')
    axes[0].set_ylabel(r'$g_{TT}$')
    axes[0].set_title(r'(a) $g_{TT} = 1 - v^2$', fontsize=11)
    axes[0].legend(fontsize=9)

    gTT_int_surf = 1 - (H * R_surface)**2
    gTT_ext_surf = 1 - 2 * M / R_surface
    axes[0].plot(R_surface / M, gTT_int_surf, 'ko', ms=6, zorder=5)
    print(f"  g_TT continuity: int={gTT_int_surf:.6f}, ext={gTT_ext_surf:.6f}, "
          f"delta={abs(gTT_int_surf - gTT_ext_surf):.2e}")

    # ── Panel (b): |g_{Tr}| ──
    axes[1].plot(r_int / M, H * r_int, 'b-', lw=2, label='Interior')
    axes[1].plot(r_ext / M, np.sqrt(2 * M / r_ext), 'r-', lw=2, label='Exterior')
    axes[1].axvline(R_surface / M, color='gray', ls='--', lw=0.8, alpha=0.5)
    axes[1].set_xlabel(r'$r/M$')
    axes[1].set_ylabel(r'$|g_{Tr}|$')
    axes[1].set_title(r'(b) $|g_{Tr}| = |v|$', fontsize=11)
    axes[1].legend(fontsize=9)

    gTr_int_surf = H * R_surface
    gTr_ext_surf = np.sqrt(2 * M / R_surface)
    axes[1].plot(R_surface / M, gTr_int_surf, 'ko', ms=6, zorder=5)
    print(f"  g_Tr continuity: int={gTr_int_surf:.6f}, ext={gTr_ext_surf:.6f}, "
          f"delta={abs(gTr_int_surf - gTr_ext_surf):.2e}")

    # ── Panel (c): g_{rr} ──
    axes[2].plot(r_int / M, np.ones_like(r_int), 'b-', lw=2, label='Interior')
    axes[2].plot(r_ext / M, np.ones_like(r_ext), 'r-', lw=2, label='Exterior')
    axes[2].axvline(R_surface / M, color='gray', ls='--', lw=0.8, alpha=0.5)
    axes[2].set_xlabel(r'$r/M$')
    axes[2].set_ylabel(r'$g_{rr}$')
    axes[2].set_title(r'(c) $g_{rr} = +1$', fontsize=11)
    axes[2].legend(fontsize=9)
    axes[2].set_ylim(0.7, 1.3)

    fig.tight_layout(w_pad=1.0)
    fig.savefig(os.path.join(FIGDIR, 'figS1_metric_continuity.pdf'))
    fig.savefig(os.path.join(FIGDIR, 'figS1_metric_continuity.png'))
    plt.close(fig)
    print("Figure S1: Metric continuity — done.")


# ══════════════════════════════════════════════════════════════════════
# Run all figures
# ══════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    print("Generating figures for OS gauge continuity paper...\n")
    fig_lapse_comparison()
    fig_velocity_field()
    # fig_spacetime_diagram()  # auxiliary; not included in manuscript
    fig_metric_continuity()
    print(f"\nAll figures generated in {FIGDIR}")
    
    print("\nSchwarzschild lapse gap (Table S4.2):")
    for R in (10.0, 5.0, 3.0, 2.5, 2.1, 2.0):   # R in units of M
        N = np.sqrt(1 - rs / R)
        print(f"  R = {R:4.1f}M:  N_Sch = {N:.4f}   dN = {1 - N:.4f}")
